In [2]:
import numpy as np
l = [1,2,3,4,5,6]
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [27]:
l1 = [4,5,6,7,"ravi", 35.55, True]
a1=np.array(l1)
a1

array(['4', '5', '6', '7', 'ravi', '35.55', 'True'], dtype='<U32')

In [25]:
a2 = np.array([[1,2,3,],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
a[0][1]

2

In [15]:
b= np.array([[[1,2,3,],[4,5,6],[7,8,9]]])
b

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [17]:
b[0][1]

array([4, 5, 6])

In [20]:
b.ndim #shows the dimension of array

3

In [22]:
b.size #it gives total number of Elements

9

In [31]:
a1.shape #one row data

(7,)

In [29]:
a2.shape #two rows and 3 columns

(2, 3)

In [30]:
b.shape  # 1 matrices which has Three rows and Three columns

(1, 3, 3)

In [38]:
a3= np.random.randint(1,40,5) # it will generate 5 element between 1 and 40
a3

array([ 5, 15,  5, 28, 20])

In [39]:
a3.ndim

1

In [41]:
a3.size #count of element

5

In [42]:
a3.shape

(5,)

In [46]:
a4= np.random.randint(1,40,(5,3,4)) # it will generate 3*4 matrix  5 times with element values between 1 and 40
a4

array([[[12,  5, 30,  6],
        [ 6, 35, 21,  8],
        [24,  8,  1, 17]],

       [[17, 27, 17, 33],
        [23, 35, 12,  4],
        [26, 29,  5,  8]],

       [[ 5, 17, 21,  9],
        [37, 29, 10,  6],
        [30, 23, 30,  4]],

       [[28, 10, 19, 13],
        [17, 24,  1,  9],
        [10, 35,  8,  2]],

       [[32, 17, 38, 36],
        [33, 12, 18, 22],
        [37, 38,  8,  1]]])

In [49]:
a5= np.random.randn(4,5)
a5

array([[-0.15875852,  0.04598456, -1.34914654,  1.05231943,  0.62619795],
       [ 0.60029216, -0.82483586, -1.12291817,  0.78933194, -1.59201896],
       [-0.62039862,  0.07060296,  1.36123925,  0.97940353,  0.20424369],
       [-1.05706928,  0.94783634,  0.06276953,  1.64508679, -0.51330256]])

In [54]:
a5.resize(5,4) # it will change 4 *5  matrix into 5*4  matrix
a5

array([[-0.15875852,  0.04598456, -1.34914654,  1.05231943],
       [ 0.62619795,  0.60029216, -0.82483586, -1.12291817],
       [ 0.78933194, -1.59201896, -0.62039862,  0.07060296],
       [ 1.36123925,  0.97940353,  0.20424369, -1.05706928],
       [ 0.94783634,  0.06276953,  1.64508679, -0.51330256]])

In [55]:
a5.reshape(5,4) # it will change 4 *5  matrix into 5*4  matrix

array([[-0.15875852,  0.04598456, -1.34914654,  1.05231943],
       [ 0.62619795,  0.60029216, -0.82483586, -1.12291817],
       [ 0.78933194, -1.59201896, -0.62039862,  0.07060296],
       [ 1.36123925,  0.97940353,  0.20424369, -1.05706928],
       [ 0.94783634,  0.06276953,  1.64508679, -0.51330256]])

In [57]:
a6= np.random.randn(4,4) #it generate 4*4 array
a6

array([[-0.37431503,  0.08143088, -0.11101795,  1.1074167 ],
       [ 2.16442375, -0.40638988, -1.33553341, -0.31147538],
       [ 0.9876719 ,  0.608294  ,  0.43404881, -1.5305096 ],
       [-1.65542064, -0.24416621,  0.430117  ,  0.18042619]])

In [70]:
a6.reshape(2,8) #it will reshape 4 *4 array into 2 * 8 array

array([[-0.37431503,  0.08143088, -0.11101795,  1.1074167 ,  2.16442375,
        -0.40638988, -1.33553341, -0.31147538],
       [ 0.9876719 ,  0.608294  ,  0.43404881, -1.5305096 , -1.65542064,
        -0.24416621,  0.430117  ,  0.18042619]])

In [73]:
a6.reshape(2,-1111111) # we can give any negative number and it will pick dimension automatically

array([[-0.37431503,  0.08143088, -0.11101795,  1.1074167 ,  2.16442375,
        -0.40638988, -1.33553341, -0.31147538],
       [ 0.9876719 ,  0.608294  ,  0.43404881, -1.5305096 , -1.65542064,
        -0.24416621,  0.430117  ,  0.18042619]])

In [72]:
a6.reshape(2,2,4) # it will reshape 2 dimension array 4 *4 into 3 dimension array of 2 * 4 with 2such instances

array([[[-0.37431503,  0.08143088, -0.11101795,  1.1074167 ],
        [ 2.16442375, -0.40638988, -1.33553341, -0.31147538]],

       [[ 0.9876719 ,  0.608294  ,  0.43404881, -1.5305096 ],
        [-1.65542064, -0.24416621,  0.430117  ,  0.18042619]]])

In [65]:
a6.reshape(8,1,2) # it will reshape 2 dimension array 4 *4 into 3 dimension array of 1 * 2 with 8 such instances

array([[[-0.37431503,  0.08143088]],

       [[-0.11101795,  1.1074167 ]],

       [[ 2.16442375, -0.40638988]],

       [[-1.33553341, -0.31147538]],

       [[ 0.9876719 ,  0.608294  ]],

       [[ 0.43404881, -1.5305096 ]],

       [[-1.65542064, -0.24416621]],

       [[ 0.430117  ,  0.18042619]]])

In [77]:
a6

array([[-0.37431503,  0.08143088, -0.11101795,  1.1074167 ],
       [ 2.16442375, -0.40638988, -1.33553341, -0.31147538],
       [ 0.9876719 ,  0.608294  ,  0.43404881, -1.5305096 ],
       [-1.65542064, -0.24416621,  0.430117  ,  0.18042619]])

In [74]:
a6[0]

array([-0.37431503,  0.08143088, -0.11101795,  1.1074167 ])

In [76]:
a6[1]

array([ 2.16442375, -0.40638988, -1.33553341, -0.31147538])

In [78]:
a6[1][2]

-1.3355334112772947

In [82]:
a6[1][:3:1]

array([ 2.16442375, -0.40638988, -1.33553341])

In [84]:
a6[::-1] #reversing array completely

array([[-1.65542064, -0.24416621,  0.430117  ,  0.18042619],
       [ 0.9876719 ,  0.608294  ,  0.43404881, -1.5305096 ],
       [ 2.16442375, -0.40638988, -1.33553341, -0.31147538],
       [-0.37431503,  0.08143088, -0.11101795,  1.1074167 ]])

In [91]:
a6

array([[-0.37431503,  0.08143088, -0.11101795,  1.1074167 ],
       [ 2.16442375, -0.40638988, -1.33553341, -0.31147538],
       [ 0.9876719 ,  0.608294  ,  0.43404881, -1.5305096 ],
       [-1.65542064, -0.24416621,  0.430117  ,  0.18042619]])

In [99]:
a6.shape

(4, 4)

In [100]:
a6[:,[1,2]]

array([[ 0.08143088, -0.11101795],
       [-0.40638988, -1.33553341],
       [ 0.608294  ,  0.43404881],
       [-0.24416621,  0.430117  ]])

In [101]:
a7= np.random.randint(1,40,(5,4)) # it will generate 5*4 matrix with element values between 1 and 40
a7

array([[17, 30,  1,  4],
       [15, 37,  3, 36],
       [18, 17, 29,  8],
       [39, 39, 20, 11],
       [15, 30, 30, 29]])

In [103]:
a7[a7>20] #extract list of all elements with value > 20

array([30, 37, 36, 29, 39, 39, 30, 30, 29])

In [107]:
a7[0][1] = 120 #changing value of elements at 0th row and 1 column  from 30 to 120
a7

array([[ 17, 120,   1,   4],
       [ 15,  37,   3,  36],
       [ 18,  17,  29,   8],
       [ 39,  39,  20,  11],
       [ 15,  30,  30,  29]])

In [110]:
a7[a7>=120] #extract list of all elements with value >= 120

array([120])

In [112]:
a8 = np.random.randint(0,3,(3,2))
a8

array([[0, 0],
       [0, 0],
       [2, 0]])

In [113]:
a9 = np.random.randint(0,3,(3,2))
a9

array([[2, 0],
       [0, 2],
       [2, 0]])

In [115]:
a8* a9 # we are multiplying values between  a8 and a9 element by element based on its position

array([[0, 0],
       [0, 0],
       [4, 0]])

In [116]:
a10 = np.random.randint(0,3,(3,2))
a10

array([[0, 2],
       [2, 1],
       [2, 2]])

In [117]:
a11 = np.random.randint(0,3,(2,3))
a11

array([[2, 1, 0],
       [0, 2, 1]])

In [122]:
a12 = a10 @ a11 # @ symbol gives matrix multiplication
a12

array([[0, 4, 2],
       [4, 4, 1],
       [4, 6, 2]])

In [123]:
a12/2

array([[0. , 2. , 1. ],
       [2. , 2. , 0.5],
       [2. , 3. , 1. ]])

In [127]:
np.zeros((2)) #it will create 1 dimension array with all element value of 0

array([0., 0.])

In [128]:
np.zeros((3,5))  #it will create 4*4 dimension array with all element value of 0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [131]:
a13= np.ones((4,9)) #it will create 4*9 dimension array with all element value as 1
a13

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [134]:
a13 + np.array([1,2,3,4,5,6,7,8,9]) # all rows of 4*9 dimension array is added with value given in second array

array([[ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [141]:
a14= np.array([[1,2,3,4]]).T  # it will transpose the 1*4 matrix to 4*1
a14

array([[1],
       [2],
       [3],
       [4]])

In [144]:
a14.resize(4,1)
a14

array([[1],
       [2],
       [3],
       [4]])

In [140]:
a13+ a14

array([[2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [148]:
list(range(0,5,2))

[0, 2, 4]

In [154]:
np.arange(1,10,3) #in numpy we have arange as compared to arange

array([1, 4, 7])

In [153]:
np.arange(1,10,3.5)

array([1. , 4.5, 8. ])

In [157]:
np.linspace(2,4,50) # it will generate 50 numbers in equal segments between 2 and 4

array([2.        , 2.04081633, 2.08163265, 2.12244898, 2.16326531,
       2.20408163, 2.24489796, 2.28571429, 2.32653061, 2.36734694,
       2.40816327, 2.44897959, 2.48979592, 2.53061224, 2.57142857,
       2.6122449 , 2.65306122, 2.69387755, 2.73469388, 2.7755102 ,
       2.81632653, 2.85714286, 2.89795918, 2.93877551, 2.97959184,
       3.02040816, 3.06122449, 3.10204082, 3.14285714, 3.18367347,
       3.2244898 , 3.26530612, 3.30612245, 3.34693878, 3.3877551 ,
       3.42857143, 3.46938776, 3.51020408, 3.55102041, 3.59183673,
       3.63265306, 3.67346939, 3.71428571, 3.75510204, 3.79591837,
       3.83673469, 3.87755102, 3.91836735, 3.95918367, 4.        ])

In [158]:
np.logspace(2,4,num=4,base=10)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [162]:
np.eye(10) # Identity matrix of 10 *10 with diagonal value as 1

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])