In [1]:
import numpy as np

In [58]:
#creating a 1 dimensional array using Numpy

np1 = np.array([1,2,3,4,5])
np1

array([1, 2, 3, 4, 5])

In [5]:
type(np.array([1,2,3,4,5])) #type is n dimensional array

numpy.ndarray

In [10]:
np.array([1,2,3.0,4]) # since we have one floating point number, it has converted all data into floating point format

array([1., 2., 3., 4.])

In [11]:
np.array([1,2,3,"ravi",3.0,4]) # since we have one string data, it has converted all data into string format

array(['1', '2', '3', 'ravi', '3.0', '4'], dtype='<U32')

In [36]:
#creating a 2 dimensional array using Numpy

np2 =np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
np2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [71]:
#fetching single element of 2dimensional Array
#first block will try to fetch element from the 2nd index row  that is 3rd row
#second block will try to fetch from 1st index column, ie 2nd column

np2[2][1]

8

In [60]:
#we can create a 2-Dimension array with  elements in haphazard columnar fashion

np2_1 =np.array([[1,2],[3,4,5,6],[7,8,9,10,11],[12]])
np2_1

C:\Users\Ravi0dubey\AppData\Local\Temp/ipykernel_25888/642223828.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np2_1 =np.array([[1,2],[3,4,5,6],[7,8,9,10,11],[12]])


array([list([1, 2]), list([3, 4, 5, 6]), list([7, 8, 9, 10, 11]),
       list([12])], dtype=object)

In [61]:
#It will fetch element from 1st index row and 3rd index column
np2_1[1][3]

6

In [82]:
#we can create a 3 dimensional array 

np3 =np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
np3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [86]:
# It will give dimension of array, which is 3 dimension
np3.ndim

3

In [88]:
# It will give size of array, how many elements are there in array

np3.size

18

In [89]:
#it will give shape of array 

#in below case we have 3 occurrence of 2 rows and 3 columns

np3.shape

(3, 2, 3)

In [73]:
#fetching single element of 3-D Array

#first block will try to fetch element from the 2nd array from the array list
#Second block will try to fetch element from the 1st index row  that is 2nd row
#Third block will try to fetch from 2nd index column, ie 3rd column

np3[1][0][2]

9

In [85]:
#Creaing a 3-D Array


np3_1 =np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]],[[111,222,333],[444,555,666]],[[777,888,999],[1010,1111,1212]],[[1313,1414,1515],[1616,1717,1818]]])
np3_1

array([[[   1,    2,    3],
        [   4,    5,    6]],

       [[   7,    8,    9],
        [  10,   11,   12]],

       [[  13,   14,   15],
        [  16,   17,   18]],

       [[ 111,  222,  333],
        [ 444,  555,  666]],

       [[ 777,  888,  999],
        [1010, 1111, 1212]],

       [[1313, 1414, 1515],
        [1616, 1717, 1818]]])

In [84]:
#fetching single element of 3-D Array

#first block will try to fetch element from the 4th array from the array list
#Second block will try to fetch element from the 1st index row  that is 2nd row
#Third block will try to fetch from 2nd index column, ie 3rd column

np3_1[3][0][2]

333

In [161]:
#default data type of integer element in an array is int32

type(np3_1[3][0][2])

numpy.int32

In [91]:
#creating a 4 dimensional array using Numpy

np2 =np.array([[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]],[[[111,222,333],[444,555,666]],[[777,888,999],[1010,1111,1212]]]])
np2

array([[[[   1,    2,    3],
         [   4,    5,    6]],

        [[   7,    8,    9],
         [  10,   11,   12]]],


       [[[ 111,  222,  333],
         [ 444,  555,  666]],

        [[ 777,  888,  999],
         [1010, 1111, 1212]]]])

In [105]:
#fetching single element of 4-D Array

#First block will try to fetch 2nd, 3-d array from the array list
#Second block will try to fetch element from the 2nd 3-d array from the array list
#Third block will try to fetch element from the 0th index row  that is 1st row
#Fourth block will try to fetch from 2nd index column, ie 3rd column

np2[1][0][0][2]

333

In [112]:
#we can create 1st, 2nd , 3rd, 4th dimensional array using below syntax

npd1 = np.array([1,2,3], ndmin = 1)
npd1

array([1, 2, 3])

In [113]:
npd2 = np.array([1,2,3], ndmin = 2)
npd2

array([[1, 2, 3]])

In [114]:
npd3 = np.array([1,2,3], ndmin = 3)
npd3

array([[[1, 2, 3]]])

In [120]:
npd4 = np.array([1,2,3], ndmin = 4)
npd4

array([[[[1, 2, 3]]]])

In [124]:
npd4[0][0][0][2]

3

In [126]:
#we can create 2nd dimensional array of data type complex using below syntax

npd2_2j = np.array([1,2,3], ndmin = 2, dtype = complex)
npd2_2j

array([[1.+0.j, 2.+0.j, 3.+0.j]])

In [148]:
#data is stored in form of tuples
# first element of the tuple will be of type int16, second element is of type int32

np2_2t = np.array([(1,2),(4,5)],dtype = [("a",'<i2'),("b",'<i4')])
np2_2t

array([(1, 2), (4, 5)], dtype=[('a', '<i2'), ('b', '<i4')])

In [154]:
np2_2t[0][0]

1

In [149]:
type(np2_2t[0][0])

numpy.int16

In [155]:
np2_2t[0][1]

2

In [150]:
type(np2_2t[0][1])

numpy.int32

In [153]:
#even if we store element in form of list, it will be stored as tuples internally

np2_2t1 = np.array([[1,2],[4,5]],dtype = [("a",'<i2'),("b",'<i4')])
np2_2t1

array([[(1, 1), (2, 2)],
       [(4, 4), (5, 5)]], dtype=[('a', '<i2'), ('b', '<i4')])

In [152]:
np2_2t1[0][1][1]

2

In [159]:
type(np2_2t1[0][0][1])

numpy.int32

In [165]:
#creating a 2 dimensional array

npa1 = np.array([[1,2,3],[4,5,6]])
npa1

array([[1, 2, 3],
       [4, 5, 6]])

In [184]:
#accessing data from 1st index row and 2nd index column
npa1[1][2]

6

# Matrix

In [185]:
#storing same array in a matrix

npm1 = np.matrix(npa1)
npm1

matrix([[1, 2, 3],
        [4, 5, 6]])

In [186]:
#accessing first index row of matrix

npm1[1]

matrix([[4, 5, 6]])

In [187]:
#if we try to access element from 1st index row and 2nd index column of matrix we will get an error

npm1[1][2]

IndexError: index 2 is out of bounds for axis 0 with size 1

In [236]:
# Matrix is subclass of array

issubclass(np.matrix,np.ndarray)

True

In [235]:
# Array is not subclass of Matrix

issubclass(np.ndarray,np.matrix)

False

# asarray

In [202]:
#asarray function will convert any data into array form
#storing array npa1 as array using asa

npasar1 = np.asarray(npa1)
npasar1

array([[1, 2, 3],
       [4, 5, 6]])

In [193]:
#fetching values from npasar1 afer its conversion to array

npasar1[1][2]

6

In [199]:
#asarray function will convert any data into array form
# It converts matrix element into an array format

npasar2 = np.asarray(npm1)
npasar2

array([[1, 2, 3],
       [4, 5, 6]])

In [201]:
# after conversion of Matrix into array, we will be able to fetch value from previously defined matrix
npasar2[1][2]

6

In [212]:
#asarray function converts list into array

list1 = [1,2,3,4,5]
npasar3 =np.asarray(list1)
npasar3

array([1, 2, 3, 4, 5])

# asanyarray

In [219]:
# asanyarray will see data type of element. If element is already available in array or matrix format,
# it will keep as it is or will convert the element into array format

#storing array npa1 as any array

npasanar1 = np.asanyarray(npa1)
npasanar1

array([[1, 2, 3],
       [4, 5, 6]])

In [222]:
npasanar1[0][2]

3

In [224]:
# asanyarray will see data type of element. If its not in array or matrix format, it will convert the element
#storing list List1 as array using asanyarray function

list1 = [1,2,3,4,5]
npasanar2 =np.asanyarray(list1)
npasanar2

array([1, 2, 3, 4, 5])

In [227]:
npasanar2[0]

1

In [230]:
# asanyarray will see data type of element. If element is already available in array or matrix format,
# it will keep as it is or will convert the element into array format

#storing array npm1 as any array

npasanar3 = np.asanyarray(npm1)
npasanar3

matrix([[1, 2, 3],
        [4, 5, 6]])

In [231]:
npasanar3[1]

matrix([[4, 5, 6]])

In [4]:
arr = np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [5]:
# it is called shallow copy
a = arr

In [6]:
# it is called deep copy
b = np.copy(arr)

In [8]:
# Lets change value of 1st element of array from 1 to 67
arr[0][0]= 67
arr

array([[67,  2],
       [ 3,  4]])

In [11]:
# If arr element got changed, it will reflect in assigned variable a as array a will still refer to original variable loc

a

array([[67,  2],
       [ 3,  4]])

In [12]:
# If arr element got changed, it will not reflect in copied array b as b is a new entity
b

array([[1, 2],
       [3, 4]])

# fromfunction

In [40]:
np.fromfunction(lambda i,j : i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [41]:
np.fromfunction(lambda i,j : i**j,(4,4))

array([[ 1.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  2.,  4.,  8.],
       [ 1.,  3.,  9., 27.]])

In [47]:
k= [i*i for i in range(5)]
k

[0, 1, 4, 9, 16]

In [48]:
type(k)

list

# Fromiter

In [65]:
gen = (i*i for i in range(5))
gen

<generator object <genexpr> at 0x0000027A29BB83C0>

In [50]:
type(gen)

generator

In [62]:
np.fromiter(gen,dtype = int)

array([ 0,  1,  4,  9, 16])

In [64]:
np.fromiter(gen, dtype = float)

array([ 0.,  1.,  4.,  9., 16.])

In [67]:
np.fromiter(range(10),dtype = int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# fromstring

In [74]:
np.fromstring('1, 2, 77, 18, 7', sep =',' ,dtype = int)

array([ 1,  2, 77, 18,  7])

In [80]:
np.fromstring('1 2 77 18 7', sep =' ' ,dtype = int)

array([ 1,  2, 77, 18,  7])

# RANGE and ARANGE

In [104]:
#creating a list of data starting from 6 till upperbound of 15 with step size of 2

list(range(6,15,2))

[6, 8, 10, 12, 14]

In [100]:
# range function will not work for floating point data

list(range(6.5,15,.2))

TypeError: 'float' object cannot be interpreted as an integer

In [103]:
# arange will work for both integer and floating values

np.arange(6,15,2)

array([ 6,  8, 10, 12, 14])

In [101]:
# arange will work for floating point

np.arange(6.5,15,.2)

array([ 6.5,  6.7,  6.9,  7.1,  7.3,  7.5,  7.7,  7.9,  8.1,  8.3,  8.5,
        8.7,  8.9,  9.1,  9.3,  9.5,  9.7,  9.9, 10.1, 10.3, 10.5, 10.7,
       10.9, 11.1, 11.3, 11.5, 11.7, 11.9, 12.1, 12.3, 12.5, 12.7, 12.9,
       13.1, 13.3, 13.5, 13.7, 13.9, 14.1, 14.3, 14.5, 14.7, 14.9])

# linspace

In [106]:
#it will generate data in floating point in range of 1 and 4
np.linspace(1,4)

array([1.        , 1.06122449, 1.12244898, 1.18367347, 1.24489796,
       1.30612245, 1.36734694, 1.42857143, 1.48979592, 1.55102041,
       1.6122449 , 1.67346939, 1.73469388, 1.79591837, 1.85714286,
       1.91836735, 1.97959184, 2.04081633, 2.10204082, 2.16326531,
       2.2244898 , 2.28571429, 2.34693878, 2.40816327, 2.46938776,
       2.53061224, 2.59183673, 2.65306122, 2.71428571, 2.7755102 ,
       2.83673469, 2.89795918, 2.95918367, 3.02040816, 3.08163265,
       3.14285714, 3.20408163, 3.26530612, 3.32653061, 3.3877551 ,
       3.44897959, 3.51020408, 3.57142857, 3.63265306, 3.69387755,
       3.75510204, 3.81632653, 3.87755102, 3.93877551, 4.        ])

In [107]:
# it will generate 3 data between 1 and 4. so most likely data will be at equal interval 

np.linspace(1,4,3)

array([1. , 2.5, 4. ])

In [109]:
# it will generate 5 data between 1 and 4. with interval size of .75

np.linspace(1,4,5)

array([1.  , 1.75, 2.5 , 3.25, 4.  ])

In [138]:
#it will by default include the upper bound element. 4 in this case

np.linspace(2,4,4, endpoint =True)

array([2.        , 2.66666667, 3.33333333, 4.        ])

In [136]:
#it will omit the upper bound element. 4 in this case

np.linspace(2,4,4, endpoint =False)

array([2. , 2.5, 3. , 3.5])

# zeros and ones

In [111]:
#it will create an 1 dimension array with all element as zeros

np.zeros(4)

array([0., 0., 0., 0.])

In [115]:
#it will create an 2 dimension array (4 *2) with all element as zeros

np.zeros([4,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [117]:
# It will create an 3 dimension array of (4 *2) with all element as zeros

np.zeros([3,4,2])

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [121]:
#it will create an 1 dimension array with all element as ones

np.ones(4)

array([1., 1., 1., 1.])

In [119]:
#it will create an 2 dimension array (4 *2) with all element as ones

np.ones([4,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [120]:
# It will create an 3 dimension array of (4 *2) with all element as ones

np.ones([3,4,2])

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [124]:
# It will create an 3 dimension array of (4 *2) with all element as ones and then 4 to each element

np.ones([3,4,2]) + 4

array([[[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]]])

In [128]:
#it will create identity matrix of 5 * 5 with value 1 at (0,0),(1,1),(2,2),(3,3),(4,4) index and rest has 0's in it

np.eye(5) 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [130]:
#add value 7 to each element
np.eye(5) + 7

array([[8., 7., 7., 7., 7.],
       [7., 8., 7., 7., 7.],
       [7., 7., 8., 7., 7.],
       [7., 7., 7., 8., 7.],
       [7., 7., 7., 7., 8.]])

# Reshape

In [153]:
# creating 2 dimensional array
d = np.array([[1,5,4,32],[3,8,9,10]])
d

array([[ 1,  5,  4, 32],
       [ 3,  8,  9, 10]])

In [155]:
#To acces element 9 from this 2 d array
d[1,2]

9

In [162]:
# We can reshape the existing 2 dimensional array using reshape function into 4 *2

d1=d.reshape(4,2)
d1

array([[ 1,  5],
       [ 4, 32],
       [ 3,  8],
       [ 9, 10]])

In [175]:
#dimension of array d1 still remains 2 d, but yes its matrix gets changed from 2 *4 to 4 *2

d1.ndim

2

In [176]:
#To acces element 9 from this 2 d array d1

d1[3,0]

9

In [185]:
# We can reshape the existing 2 dimensional array  into 3 d using reshape function into 1*1*8

d2 = d.reshape(1,1,8)
d2

array([[[ 1,  5,  4, 32,  3,  8,  9, 10]]])

In [173]:
# dimension is 3 D
d2.ndim

3

In [174]:
# Fetching element from 3 d array

d2[0,0,2]

4

In [186]:
# We can give any negative element as the last element and it will figure out automatically what would be the dimension
# Over here we have 8 elements and we have asked to convert into 3-D array 
# so -1 gets converted to 4, so it become 2 * 4

d3 = d.reshape(1,2,-1)
d3

array([[[ 1,  5,  4, 32],
        [ 3,  8,  9, 10]]])

In [188]:
# We can give any negative element as the last element and it will figure out automatically what would be the dimension
# Over here we have 8 elements and we have asked to convert into 3-D array 
# so -1 gets converted to 2, so it become 4 * 2 array

d4 = d.reshape(1,4,-1)
d4

array([[[ 1,  5],
        [ 4, 32],
        [ 3,  8],
        [ 9, 10]]])

In [189]:
# will give maximum value in the array

d4.max()

32

In [191]:
# will give minimum value in the array

d4.min()

1

# Data fetching from Array

In [203]:
np.random.seed()
d5= np.random.randint(4,100,(5,5))
d5

array([[76, 27, 26,  5, 75],
       [73, 82, 76, 33, 89],
       [ 7, 86, 31, 56, 61],
       [86, 88,  6,  9, 25],
       [43, 32, 54, 42,  6]])

In [253]:
# in case we need to fetch any element of array
# we can give row number and till what row we want data from it
# we can give column number and till what column we want data from it
# so it gives 2 * 2 dimension array

d6= d5[2:4,1:3]
d6

array([[86, 31],
       [88,  6]])

In [269]:
# if we need column 1st and 3rd index we can give row as constant and columnar data can be handpicked by giving the number

d7 = d5[:,[1,3]]
d7

array([[27,  5],
       [82, 33],
       [86, 56],
       [88,  9],
       [32, 42]])

In [279]:
#we can give condition to figure out what all elements are greater than 10

d5>10

array([[ True,  True,  True, False,  True],
       [ True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True],
       [ True,  True, False, False,  True],
       [ True,  True,  True,  True, False]])

In [283]:
# To get a value of elements we can give following condition

d8=d5[d5>10]
d8

array([76, 27, 26, 75, 73, 82, 76, 33, 89, 86, 31, 56, 61, 86, 88, 25, 43,
       32, 54, 42])

In [284]:
d8.reshape(5,4)

array([[76, 27, 26, 75],
       [73, 82, 76, 33],
       [89, 86, 31, 56],
       [61, 86, 88, 25],
       [43, 32, 54, 42]])

In [289]:
# reshaping the array into 4 * 5
d5[d5>10].reshape(4,-1)

array([[76, 27, 26, 75, 73],
       [82, 76, 33, 89, 86],
       [31, 56, 61, 86, 88],
       [25, 43, 32, 54, 42]])

# Arithmetic Operations on Array

Arithmentic operations will take place on each individual elements of array at the particualar index

In [294]:
d9 = np.random.randint(2,6,(3,3))
d9

array([[5, 5, 5],
       [5, 4, 3],
       [3, 3, 2]])

In [295]:
d10 = np.random.randint(5,9,(3,3))
d10

array([[7, 5, 7],
       [7, 8, 8],
       [6, 5, 6]])

In [296]:
# 
d9*d10

array([[35, 25, 35],
       [35, 32, 24],
       [18, 15, 12]])

In [297]:
d9+d10

array([[12, 10, 12],
       [12, 12, 11],
       [ 9,  8,  8]])

In [298]:
d9-d10

array([[-2,  0, -2],
       [-2, -4, -5],
       [-3, -2, -4]])

In [299]:
d9/d10

array([[0.71428571, 1.        , 0.71428571],
       [0.71428571, 0.5       , 0.375     ],
       [0.5       , 0.6       , 0.33333333]])

In [300]:
d9%d10

array([[5, 0, 5],
       [5, 4, 3],
       [3, 3, 2]], dtype=int32)

In [301]:
d9**d10

array([[78125,  3125, 78125],
       [78125, 65536,  6561],
       [  729,   243,    64]], dtype=int32)

In [314]:
# this is real matrix multiplication

#[5*7 + 5*7 + 5*6 = 100]
#[5*5+5*8+ 5*5 = 90 and so on

d9@d10 

array([[100,  90, 105],
       [ 81,  72,  85],
       [ 54,  49,  57]])

In [309]:
# If array dimensions are different then no arithmetic operations are feasible

In [303]:
# 3*2 array
d11 = np.random.randint(2,6,(3,2))
d11

array([[5, 5],
       [2, 5],
       [4, 4]])

In [310]:
# 3*3 array

d12 = np.random.randint(5,13,(3,3))
d12

array([[ 7,  8,  5],
       [10, 10,  8],
       [10,  7,  6]])

In [312]:
d11 * d12

ValueError: operands could not be broadcast together with shapes (3,2) (3,3) 

In [365]:
#square root operations

np.sqrt(d9)

array([[2.23606798, 2.23606798, 2.23606798],
       [2.23606798, 2.        , 1.73205081],
       [1.73205081, 1.73205081, 1.41421356]])

In [369]:
#exponent of array

np.exp(d9)

array([[148.4131591 , 148.4131591 , 148.4131591 ],
       [148.4131591 ,  54.59815003,  20.08553692],
       [ 20.08553692,  20.08553692,   7.3890561 ]])

In [368]:
#Log10 of d9

np.log10(d9)

array([[0.69897   , 0.69897   , 0.69897   ],
       [0.69897   , 0.60205999, 0.47712125],
       [0.47712125, 0.47712125, 0.30103   ]])

# Broadcasting

In [322]:
d13 = np.ones((3,4))
d13

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [324]:
d14 = np.array([4,5,6,7])
d14

array([4, 5, 6, 7])

In [344]:
# Row wise Broadcasting

# it will broadcast or sum up the element of d14 with d13
d13+d14

array([[5., 6., 7., 8.],
       [5., 6., 7., 8.],
       [5., 6., 7., 8.]])

In [329]:
d15 = np.array([8,9,10,11,13])
d15

array([ 8,  9, 10, 11, 13])

In [331]:
#since dimension of d15 is greater than d13, addition operation will not work
d13 + d15

ValueError: operands could not be broadcast together with shapes (3,4) (5,) 

In [342]:
d16 = np.random.randint(4,99,(3,1))
d16

array([[45],
       [77],
       [ 4]])

In [345]:
# column wise broadcasting

d13+d16

array([[46., 46., 46., 46.],
       [78., 78., 78., 78.],
       [ 5.,  5.,  5.,  5.]])

In [350]:
d17= np.array([3,11,12]).reshape(3,1)
d17

array([[ 3],
       [11],
       [12]])

In [352]:
# column wise broadcasting

d13+d17

array([[ 4.,  4.,  4.,  4.],
       [12., 12., 12., 12.],
       [13., 13., 13., 13.]])

In [357]:
d18 = np.array([[3,11,12]])
d18

array([[ 3, 11, 12]])

In [358]:
#It will transpose the 2 dimension array
d18.T


array([[ 3],
       [11],
       [12]])

In [362]:
# column wise broadcasting using Transpose operations

d13 +d18.T

array([[ 4.,  4.,  4.,  4.],
       [12., 12., 12., 12.],
       [13., 13., 13., 13.]])

In [363]:
d13

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])