In [1]:
import numpy as np

In [58]:
#creating a 1 dimensional array using Numpy

np1 = np.array([1,2,3,4,5])
np1

array([1, 2, 3, 4, 5])

In [5]:
type(np.array([1,2,3,4,5])) #type is n dimensional array

numpy.ndarray

In [10]:
np.array([1,2,3.0,4]) # since we have one floating point number, it has converted all data into floating point format

array([1., 2., 3., 4.])

In [11]:
np.array([1,2,3,"ravi",3.0,4]) # since we have one string data, it has converted all data into string format

array(['1', '2', '3', 'ravi', '3.0', '4'], dtype='<U32')

In [36]:
#creating a 2 dimensional array using Numpy

np2 =np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
np2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [71]:
#fetching single element of 2dimensional Array
#first block will try to fetch element from the 2nd index row  that is 3rd row
#second block will try to fetch from 1st index column, ie 2nd column

np2[2][1]

8

In [60]:
#we can create a 2-Dimension array with  elements in haphazard columnar fashion

np2_1 =np.array([[1,2],[3,4,5,6],[7,8,9,10,11],[12]])
np2_1

C:\Users\Ravi0dubey\AppData\Local\Temp/ipykernel_25888/642223828.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np2_1 =np.array([[1,2],[3,4,5,6],[7,8,9,10,11],[12]])


array([list([1, 2]), list([3, 4, 5, 6]), list([7, 8, 9, 10, 11]),
       list([12])], dtype=object)

In [61]:
#It will fetch element from 1st index row and 3rd index column
np2_1[1][3]

6

In [69]:
#we can create a 3 dimensional array 

np3 =np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
np3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [73]:
#fetching single element of 3-D Array

#first block will try to fetch element from the 2nd array from the array list
#Second block will try to fetch element from the 1st index row  that is 2nd row
#Third block will try to fetch from 2nd index column, ie 3rd column

np3[1][0][2]

9

In [85]:
#Creaing a 3-D Array


np3_1 =np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]],[[111,222,333],[444,555,666]],[[777,888,999],[1010,1111,1212]],[[1313,1414,1515],[1616,1717,1818]]])
np3_1

array([[[   1,    2,    3],
        [   4,    5,    6]],

       [[   7,    8,    9],
        [  10,   11,   12]],

       [[  13,   14,   15],
        [  16,   17,   18]],

       [[ 111,  222,  333],
        [ 444,  555,  666]],

       [[ 777,  888,  999],
        [1010, 1111, 1212]],

       [[1313, 1414, 1515],
        [1616, 1717, 1818]]])

In [84]:
#fetching single element of 3-D Array

#first block will try to fetch element from the 4th array from the array list
#Second block will try to fetch element from the 1st index row  that is 2nd row
#Third block will try to fetch from 2nd index column, ie 3rd column

np3_1[3][0][2]

333

In [161]:
#default data type of integer element in an array is int32

type(np3_1[3][0][2])

numpy.int32

In [91]:
#creating a 4 dimensional array using Numpy

np2 =np.array([[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]],[[[111,222,333],[444,555,666]],[[777,888,999],[1010,1111,1212]]]])
np2

array([[[[   1,    2,    3],
         [   4,    5,    6]],

        [[   7,    8,    9],
         [  10,   11,   12]]],


       [[[ 111,  222,  333],
         [ 444,  555,  666]],

        [[ 777,  888,  999],
         [1010, 1111, 1212]]]])

In [105]:
#fetching single element of 4-D Array

#First block will try to fetch 2nd, 3-d array from the array list
#Second block will try to fetch element from the 2nd 3-d array from the array list
#Third block will try to fetch element from the 0th index row  that is 1st row
#Fourth block will try to fetch from 2nd index column, ie 3rd column

np2[1][0][0][2]

333

In [112]:
#we can create 1st, 2nd , 3rd, 4th dimensional array using below syntax

npd1 = np.array([1,2,3], ndmin = 1)
npd1

array([1, 2, 3])

In [113]:
npd2 = np.array([1,2,3], ndmin = 2)
npd2

array([[1, 2, 3]])

In [114]:
npd3 = np.array([1,2,3], ndmin = 3)
npd3

array([[[1, 2, 3]]])

In [120]:
npd4 = np.array([1,2,3], ndmin = 4)
npd4

array([[[[1, 2, 3]]]])

In [124]:
npd4[0][0][0][2]

3

In [126]:
#we can create 2nd dimensional array of data type complex using below syntax

npd2_2j = np.array([1,2,3], ndmin = 2, dtype = complex)
npd2_2j

array([[1.+0.j, 2.+0.j, 3.+0.j]])

In [148]:
#data is stored in form of tuples
# first element of the tuple will be of type int16, second element is of type int32

np2_2t = np.array([(1,2),(4,5)],dtype = [("a",'<i2'),("b",'<i4')])
np2_2t

array([(1, 2), (4, 5)], dtype=[('a', '<i2'), ('b', '<i4')])

In [154]:
np2_2t[0][0]

1

In [149]:
type(np2_2t[0][0])

numpy.int16

In [155]:
np2_2t[0][1]

2

In [150]:
type(np2_2t[0][1])

numpy.int32

In [153]:
#even if we store element in form of list, it will be stored as tuples internally

np2_2t1 = np.array([[1,2],[4,5]],dtype = [("a",'<i2'),("b",'<i4')])
np2_2t1

array([[(1, 1), (2, 2)],
       [(4, 4), (5, 5)]], dtype=[('a', '<i2'), ('b', '<i4')])

In [152]:
np2_2t1[0][1][1]

2

In [159]:
type(np2_2t1[0][0][1])

numpy.int32

In [165]:
#creating a 2 dimensional array

npa1 = np.array([[1,2,3],[4,5,6]])
npa1

array([[1, 2, 3],
       [4, 5, 6]])

In [184]:
#accessing data from 1st index row and 2nd index column
npa1[1][2]

6

# Matrix

In [185]:
#storing same array in a matrix

npm1 = np.matrix(npa1)
npm1

matrix([[1, 2, 3],
        [4, 5, 6]])

In [186]:
#accessing first index row of matrix

npm1[1]

matrix([[4, 5, 6]])

In [187]:
#if we try to access element from 1st index row and 2nd index column of matrix we will get an error

npm1[1][2]

IndexError: index 2 is out of bounds for axis 0 with size 1

In [236]:
# Matrix is subclass of array

issubclass(np.matrix,np.ndarray)

True

In [235]:
# Array is not subclass of Matrix

issubclass(np.ndarray,np.matrix)

False

# asarray

In [202]:
#asarray function will convert any data into array form
#storing array npa1 as array using asa

npasar1 = np.asarray(npa1)
npasar1

array([[1, 2, 3],
       [4, 5, 6]])

In [193]:
#fetching values from npasar1 afer its conversion to array

npasar1[1][2]

6

In [199]:
#asarray function will convert any data into array form
# It converts matrix element into an array format

npasar2 = np.asarray(npm1)
npasar2

array([[1, 2, 3],
       [4, 5, 6]])

In [201]:
# after conversion of Matrix into array, we will be able to fetch value from previously defined matrix
npasar2[1][2]

6

In [212]:
#asarray function converts list into array

list1 = [1,2,3,4,5]
npasar3 =np.asarray(list1)
npasar3

array([1, 2, 3, 4, 5])

# asanyarray

In [219]:
# asanyarray will see data type of element. If element is already available in array or matrix format,
# it will keep as it is or will convert the element into array format

#storing array npa1 as any array

npasanar1 = np.asanyarray(npa1)
npasanar1

array([[1, 2, 3],
       [4, 5, 6]])

In [222]:
npasanar1[0][2]

3

In [224]:
# asanyarray will see data type of element. If its not in array or matrix format, it will convert the element
#storing list List1 as array using asanyarray function

list1 = [1,2,3,4,5]
npasanar2 =np.asanyarray(list1)
npasanar2

array([1, 2, 3, 4, 5])

In [227]:
npasanar2[0]

1

In [230]:
# asanyarray will see data type of element. If element is already available in array or matrix format,
# it will keep as it is or will convert the element into array format

#storing array npm1 as any array

npasanar3 = np.asanyarray(npm1)
npasanar3

matrix([[1, 2, 3],
        [4, 5, 6]])

In [231]:
npasanar3[1]

matrix([[4, 5, 6]])